services:
  redis:
    image: redis:7-alpine
    restart: always
    env_file: .env
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    env_file: .env

    depends_on:
      - redis
      - postgres

    # You can remove this fields if you don't use webhooks.
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"

volumes:
  redis-data:
  postgres-data:
